language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode9
      env:
        - ENABLE_UI=ON
        - MATRIX_EVAL="wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-mac.zip && unzip ninja-mac.zip && export PATH=$PWD:$PATH"
    - os: linux
      addons:
        apt:
          packages:
            - libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev libxi-dev ninja-build
      env:
        - ENABLE_UI=OFF
        - XVFB=xvfb-run
    - os: linux
      addons:
        apt:
          packages:
            - libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev libxi-dev ninja-build
      env:
        - ENABLE_SCRIPTING=OFF
        - XVFB=xvfb-run
    - os: linux
      addons:
        apt:
          packages:
            - libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev libxi-dev ninja-build
      env:
        - ENABLE_SCRIPTING=OFF
        - ENABLE_UI=OFF
        - SKIP_TESTS_REPO=ON
        - XVFB=xvfb-run
    - os: linux
      addons:
        apt:
          packages:
            - libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev libxi-dev ninja-build
      env:
        - ENABLE_UI=ON
        - XVFB=xvfb-run
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7 libpixman-1-dev libfreetype6-dev libharfbuzz-dev libx11-dev libxcursor-dev libxi-dev ninja-build
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
        - ENABLE_UI=ON
        - XVFB=xvfb-run

before_install:
  - eval "${MATRIX_EVAL}"

before_script:
  - mkdir build
  - cd build
  - cmake .. -G Ninja -DCMAKE_BUILD_TYPE=Debug -DENABLE_TESTS=ON -DENABLE_UI=$ENABLE_UI

script:
  - ninja
  - |
    if $XVFB ctest --output-on-failure ; then
      if [ "$SKIP_TESTS_REPO" == "" ] ; then
        export ASEPRITE=$PWD/bin/aseprite
        git clone --recursive https://github.com/aseprite/tests.git
        cd tests
        $XVFB bash run-tests.sh
      fi
    else
      exit 1
    fi
